### ISSUE TITLE
[CURATOR-165] LeaderLatch.checkLeadership(LeaderLatch.java:478) will throw a exception, then no leader will be elected.

### ISSUE THREAD

**Issue by jira-importer** [apache/infrastructure-jira-issues-import-test-curator#165]
<p>We use curator for leader election within our 2 clients, sometimes none of the 2 clients was a leader.<br/>
We checked the log and found this caused by a exception which was being throwed in method LeaderLatch.checkLeadership(), after throwing this exception the curator won't do the leader election. Here is error log:</p>

<p>ERROR org.apache.curator.framework.imps.CuratorFrameworkImpl - Background exception was not retry-able or retry gave up<br/>
INFO   | jvm 1    | 2014/11/12 00:36:52 | java.lang.IllegalArgumentException: Path must start with / character<br/>
INFO   | jvm 1    | 2014/11/12 00:36:52 | 	at org.apache.curator.utils.PathUtils.validatePath(PathUtils.java:53)<br/>
INFO   | jvm 1    | 2014/11/12 00:36:52 | 	at org.apache.curator.utils.ZKPaths.getNodeFromPath(ZKPaths.java:56)<br/>
INFO   | jvm 1    | 2014/11/12 00:36:52 | 	at org.apache.curator.framework.recipes.leader.LeaderLatch.checkLeadership(LeaderLatch.java:478)<br/>
INFO   | jvm 1    | 2014/11/12 00:36:52 | 	at org.apache.curator.framework.recipes.leader.LeaderLatch.access$500(LeaderLatch.java:60)<br/>
INFO   | jvm 1    | 2014/11/12 00:36:52 | 	at org.apache.curator.framework.recipes.leader.LeaderLatch$6.processResult(LeaderLatch.java:536)<br/>
INFO   | jvm 1    | 2014/11/12 00:36:52 | 	at org.apache.curator.framework.imps.CuratorFrameworkImpl.sendToBackgroundCallback(CuratorFrameworkImpl.java:730)<br/>
INFO   | jvm 1    | 2014/11/12 00:36:52 | 	at org.apache.curator.framework.imps.CuratorFrameworkImpl.processBackgroundOperation(CuratorFrameworkImpl.java:516)<br/>
INFO   | jvm 1    | 2014/11/12 00:36:52 | 	at org.apache.curator.framework.imps.GetChildrenBuilderImpl$2.processResult(GetChildrenBuilderImpl.java:166)<br/>
INFO   | jvm 1    | 2014/11/12 00:36:52 | 	at org.apache.zookeeper.ClientCnxn$EventThread.processEvent(ClientCnxn.java:590)<br/>
INFO   | jvm 1    | 2014/11/12 00:36:52 | 	at org.apache.zookeeper.ClientCnxn$EventThread.run(ClientCnxn.java:498)</p>

---
<details><summary><i>Originally reported by <a title="zhaogang" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zhaogang">zhaogang</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-165" target="_blank">LeaderLatch.checkLeadership(LeaderLatch.java:478) will throw a exception, then no leader will be elected.</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jordan Zimmerman" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>
<li><b>status</b>: Closed
<li><b>priority</b>: Critical
<li><b>resolution</b>: Duplicate
<li><b>resolved</b>: 2015-04-21T02:18:48+01:00
<li><b>imported</b>: 2025-01-19
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=mdrob">mdrob</a>:</i>
<p>I think this might be the same issue as described in <a href="https://issues.apache.org/jira/browse/CURATOR-136" title="Invalid LeaderLatch path never errors" class="issue-link" data-issue-key="CURATOR-136"><del>CURATOR-136</del></a>. <a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=zhaogang" class="user-hover" rel="zhaogang">zhaogang</a> - is there any chance you can upgrade to 2.7.0 and see if that fixes your problem?</p>

**Comment by jira-importer** [comment]
<i>[Duplicates: <a href="https://github.com/apache/infrastructure-jira-issues-import-test-curator/issues?q=in%3Atitle%20CURATOR-168">CURATOR-168</a>]</i>
