### ISSUE TITLE
[CURATOR-364] Persistent Node Constructor Requires a Started ZK Connection

### ISSUE THREAD

**Issue by jira-importer** [apache/infrastructure-jira-issues-import-test-curator#363]
<p><b>Steps to reproduce:</b><br/>
1. Initialise an instance of PersistentNode<br/>
2. Ensure that CuratorFramework is Not Started (Latent)</p>

<p><b>Expected behaviour:</b><br/>
PersistentNode constructor should work without an active CuratorFramework connection to ZK</p>

<p><b>Actual behaviour</b>:<br/>
An Exception is thrown:</p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">Caused by: java.lang.IllegalStateException: instance must be started before calling <span class="code-keyword">this</span> methodDEBUG [2016-12-14 10:25:25,641] akka.event.EventStream: logger log1-Slf4jLogger started

	at com.google.common.base.Preconditions.checkState(Preconditions.java:150)
	at org.apache.curator.framework.imps.CuratorFrameworkImpl.create(CuratorFrameworkImpl.java:351)
	at org.apache.curator.framework.recipes.nodes.PersistentNode.<init>(PersistentNode.java:173)
</pre>
</div></div>

<p><b>Thoughts</b><br/>
This behaviour is inconsistent with other Zk recepies based on Closable interface. PersistentNode should not attempt any Zk communication until start() method is called.</p>

---
<details><summary><i>Originally reported by <a title="Ilya Biryukov" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=iBiryukov">iBiryukov</a>, imported from: <a href="https://issues.apache.org/jira/browse/CURATOR-364" target="_blank">Persistent Node Constructor Requires a Started ZK Connection</a></i></summary>
<i><ul>
<li><b>assignee</b>: <a title="Jordan Zimmerman" href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>
<li><b>status</b>: Resolved
<li><b>priority</b>: Major
<li><b>resolution</b>: Fixed
<li><b>resolved</b>: 2017-01-09T16:28:13+00:00
<li><b>imported</b>: 2025-01-19
</ul></i>
</details>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>It's because the ctor calls client.create() early as an optimization. I agree that this should be fixed.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=ibiryukov">ibiryukov</a>:</i>
<p><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt" class="user-hover" rel="randgalt">Jordan Zimmerman</a> Yes, I saw the root cause. I'll submit a PR for this bug.</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=imesha">imesha</a>:</i>
<p>If we completely move the </p>

<div class="code panel" style="border-width: 1px;"><div class="codeContent panelContent">
<pre class="code-java">createMethod = useProtection ? client.create().creatingParentContainersIfNeeded().withProtection() : client.create().creatingParentContainersIfNeeded();
</pre>
</div></div>

<p>code segment to the <b>createNode()</b> method, will it solve the problem? Then, an exception will be raised only when you call the <b>start()</b> method of the PersistentNode without starting the client. This should be the expected behavior I guess?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>GitHub user IMS94 opened a pull request:</p>

<p>    <a href="https://github.com/apache/curator/pull/177" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/177</a></p>

<p>    <a href="https://issues.apache.org/jira/browse/CURATOR-364" title="Persistent Node Constructor Requires a Started ZK Connection" class="issue-link" data-issue-key="CURATOR-364"><del>CURATOR-364</del></a> Persistent Node Constructor Requires a Started ZK Connection</p>

<p>    I have moved the </p>

<p>    ```<br/>
    createMode= useProtection ? client.create().creatingParentContainersIfNeeded().withProtection() : client.create().creatingParentContainersIfNeeded();<br/>
    ```<br/>
    code segment to the *<b>createNode()</b>* method. Then, an exception will be raised only when you call the `start()` method of the PersistentNode without starting the client. This should be the expected behavior I guess?</p>

<p>You can merge this pull request into a Git repository by running:</p>

<p>    $ git pull <a href="https://github.com/IMS94/curator" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/IMS94/curator</a> <a href="https://issues.apache.org/jira/browse/CURATOR-364" title="Persistent Node Constructor Requires a Started ZK Connection" class="issue-link" data-issue-key="CURATOR-364"><del>CURATOR-364</del></a></p>

<p>Alternatively you can review and apply these changes as the patch at:</p>

<p>    <a href="https://github.com/apache/curator/pull/177.patch" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/177.patch</a></p>

<p>To close this pull request, make a commit to your master/trunk branch<br/>
with (at least) the following in the commit message:</p>

<p>    This closes #177</p>

<hr />
<p>commit a8a5d46cca4a6257d7f8edce9f3d21af3526847b<br/>
Author: Imesha <imesha.sudasinghe@gmail.com><br/>
Date:   2016-11-29T09:54:37Z</p>

<p>    Introduced hostname to InstanceSpec so that the TestingServer can be bound to other interfaces in a machine other than localhost (127.0.01)</p>

<p>commit 140342045e15876e610d5adee5eda5723d00f09d<br/>
Author: Imesha <imesha.sudasinghe@gmail.com><br/>
Date:   2016-12-13T02:54:00Z</p>

<p>    Merge branch 'master' of <a href="https://github.com/apache/curator" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator</a></p>

<p>commit ea710f4ed62aed1a3a8f324280d1592a7c23b8e0<br/>
Author: Imesha <imesha.sudasinghe@gmail.com><br/>
Date:   2016-12-15T07:18:15Z</p>

<p>    <a href="https://issues.apache.org/jira/browse/CURATOR-364" title="Persistent Node Constructor Requires a Started ZK Connection" class="issue-link" data-issue-key="CURATOR-364"><del>CURATOR-364</del></a> - Moved createMode=client.create() segment to createNode() method</p>

<hr />

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user ilyabiryukov-r7 commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/177" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/177</a></p>

<p>    Hey guys, are we ok to merge this?</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user asfgit closed the pull request at:</p>

<p>    <a href="https://github.com/apache/curator/pull/177" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/177</a></p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=randgalt">randgalt</a>:</i>
<p>Thank you!</p>

**Comment by jira-importer** [comment]
<i><a href="https://issues.apache.org/jira/secure/ViewProfile.jspa?name=githubbot">githubbot</a>:</i>
<p>Github user Randgalt commented on the issue:</p>

<p>    <a href="https://github.com/apache/curator/pull/177" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/pull/177</a></p>

<p>    Note: after merging I noticed that the original PR breaks nodes with protection as the protection ID is stored in the create builder. <a href="https://github.com/apache/curator/commit/0b699a368bbb5f3c72ab609fa590bf225c2a2d7a" class="external-link" target="_blank" rel="nofollow noopener">https://github.com/apache/curator/commit/0b699a368bbb5f3c72ab609fa590bf225c2a2d7a</a> fixes this</p>
